casa = float(input('Valor da casa: R$'))
salário = float(input('Salárario do comprador: R$'))
anos : int(input('Quantos anos de financiamento? '))
prestação = casa / (anos * 12)
print('Para pagar uma casa de R${:.2f} em {}anos' .format(casa, anos))
print(' a prestação será de R${:.2f}' .format(prestação))